### ISSUE TITLE
Most Recent Icon Package release causes type errors

### ISSUE THREAD

**Issue by ieedan** [seantimm/svelte-fontawesome#10]
**Describe the bug**
When upgrading to the most recent release of the icons packages `6.5.2` you get a type error when using imported icons on the `<FontAwesomeIcon>` component.

![image](https://github.com/FortAwesome/svelte-fontawesome/assets/117548273/28bd020a-c505-48a1-a80a-19c30278e145)

**Reproducible test case**
[Stack Blitz Repro](https://stackblitz.com/edit/vitejs-vite-hpaj7m?file=package.json,src%2FApp.svelte&terminal=dev)

**Expected behavior**
No type error

**Comment by ieedan** [comment]
Looks like icon type definition comes from the main package

**index.d.ts** Line 7
```js
import { IconProp } from '@fortawesome/fontawesome-svg-core'
```

**Comment by robmadole** [comment]
Hi @ieedan. Did you also upgrade `@fortawesome/fontawesome-common-types` to version 6.5.2? That should fix things up for you. I'm happy to re-open this if you are still having issues.

**Comment by ieedan** [comment]
I am not currently using `@fortawesome/fontawesome-common-types`. I went ahead and installed it @6.5.2 and the issue persists but with a new error.

![image](https://github.com/FortAwesome/svelte-fontawesome/assets/117548273/0d6a1a0f-8963-48b5-bf55-8aa15c704afb)

**Comment by robmadole** [comment]
@ieedan how can I see this error on the reproducible test case you provided?

**Comment by ieedan** [comment]
Im not sure that stackblitz displays the error you'd have to fork it to vscode. And then install the additional dependency I haven't updated the example with the common types package.

**Comment by robmadole** [comment]
I opened the Stackblitz in VS Code for the Desktop (macOS). Here is what I see:

<img width="1028" alt="33D894M7@2x" src="https://github.com/FortAwesome/svelte-fontawesome/assets/132895/4ddc5225-faf0-4eeb-b751-d386f50fa304">

**Comment by ieedan** [comment]
So I can't recreate the problem in the example but I continue to get the issue on my larger project. 

Went ahead and deleted node modules and reinstalled everything fresh and I am still getting the same issue as before.

**package.json**
```json
"@fortawesome/fontawesome-common-types": "^6.5.2",
"@fortawesome/free-brands-svg-icons": "^6.5.2",
"@fortawesome/pro-light-svg-icons": "^6.5.2",
"@fortawesome/pro-regular-svg-icons": "^6.5.2",
"@fortawesome/pro-solid-svg-icons": "^6.5.2",
"@fortawesome/svelte-fontawesome": "^0.2.2",
```

The other project is a kit project but I cant seem to recreate it in a smaller project right now.

error: 
```
Type 'IconDefinition' is not assignable to type '"fa-solid fa-function" | 
"fa-solid fa-user" | "fa-solid fa-sort" | "fa-solid fa-map" | "fa-solid fa-filter" |
 "fa-solid fa-fill" | "fa-solid fa-at" | "fa-solid fa-1" | "fa-solid fa-a" | ... 28671 more ... | IconProp'
```

**Comment by ieedan** [comment]
I'm really not sure where to go with this now. 

Going back to 6.5.1 solves it for me for now so I'll just stick with that.
