### ISSUE TITLE
Typescript: Color prop is not working and style prop cannot accept bare string (but works!) 

### ISSUE THREAD

**Issue by MartinBspheroid** [seantimm/svelte-fontawesome#11]
**Describe the bug**
When using the svelte-fontawesome package with TypeScript, passing a string to the style prop of the FontAwesomeIcon component results in a TypeScript error. The type definition for the style prop only accepts CSS.PropertiesHyphen (an object of CSS properties), but in Svelte, passing the style prop as a string is common.

Also "color" prop is mentioned in the typed definition, but it's not declared (or mentioned at all ) in FontAwesomeIcon.svelte

**Expected behavior**
I expect to pass a string to the style prop without TypeScript errors, as Svelte allows using the style attribute with a string. Alternatively, the type definition for the style prop should accept a string type in addition to CSS.PropertiesHyphen.

**Additional context**
The issue seems to stem from the type definition of the style prop in FontAwesomeIconProps:
<img width="832" alt="image" src="https://github.com/user-attachments/assets/cb262f7d-daeb-4b3e-aba9-28be896ee9be">

**Comment by robmadole** [comment]
0.2.3 released. Thanks a bunch @MartinBspheroid !
