### ISSUE TITLE
Example lockfiles contain references to npm.fontawesome.com

### ISSUE THREAD

**Issue by dbrgn** [seantimm/svelte-fontawesome#7]
**Describe the bug**

Dependencies in the example apps' lockfiles contain references to npm.fontawesome.com.

Installing the dependencies fails because it asks for a password.

I suspect this is an npm proxy used by developers of FontAwesome.

**Reproducible test case**

1. Clone repo
2. `cd examples/sveltekit-app/`
3. npm install

```
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR!
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login
```

**Expected behavior**

Dependencies can be installed without first manually removing the lockfile.

**Additional context**

This is probably a symptom of the examples not being part of CI. Since the examples are currently the only documentation, adding them to CI would be important.

**Comment by dbrgn** [comment]
Note: Simply deleting the lockfile doesn't work either:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: sveltekit-app@0.0.1
npm ERR! Found: vite@3.2.7
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^4.0.0" from @sveltejs/kit@1.0.0-next.589
npm ERR! node_modules/@sveltejs/kit
npm ERR!   dev @sveltejs/kit@"next" from the root project
npm ERR!   peer @sveltejs/kit@"^1.0.0-next.587" from @sveltejs/adapter-auto@1.0.0-next.91
npm ERR!   node_modules/@sveltejs/adapter-auto
npm ERR!     dev @sveltejs/adapter-auto@"next" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by robmadole** [comment]
@dbrgn please check your configuration. The way that these npm.fontawesome.com URLs will end up in lock files is by configuring a system to do so. Our documentation for this is here: https://fontawesome.com/docs/web/setup/packages (and it also has some troubleshooting tips).

**Comment by dbrgn** [comment]
@robmadole I'm confused... This is definitely not something I did: https://github.com/FortAwesome/svelte-fontawesome/blob/72c59bee5cde72dfb9e6a8b13d6ca953a06316c1/examples/sveltekit-app/package-lock.json#L28

Did you try the steps to reproduce on a clean system?

**Comment by robmadole** [comment]
@dbrgn Oh! No, my bad. You're talking about the examples in this repo. I'll get that fixed, you are correct those shouldn't be in there. I apologize for now reading your issue carefully enough.

**Comment by robmadole** [comment]
@dbrgn I've just updated the examples. They should be fixed up now.

**Comment by dbrgn** [comment]
@robmadole no worries! Thanks, yes, now I can get the example to run 🙂
